/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.teladlogin;

/**
 *
 * @author pedro
 */
public class telarecovery extends javax.swing.JFrame {

    /**
     * Creates new form telarecovery
     */
    public telarecovery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITULO_EMAIL_LOGIN = new javax.swing.JLabel();
        TITULO_LOGIN_SIG2 = new javax.swing.JLabel();
        LOGO_BOMPAO_LOGIN = new javax.swing.JLabel();
        TITULO_BOMPAO = new javax.swing.JLabel();
        BT_ENTRAR_LOGIN = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BT_ENTRAR_LOGIN1 = new javax.swing.JButton();
        BT_ENTRAR_LOGIN2 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TITULO_EMAIL_LOGIN1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TITULO_EMAIL_LOGIN2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        IMG_BACKGRUND_LOGIN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO_EMAIL_LOGIN.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TITULO_EMAIL_LOGIN.setForeground(new java.awt.Color(255, 243, 211));
        TITULO_EMAIL_LOGIN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TITULO_EMAIL_LOGIN.setText("Crie sua nova senha");
        getContentPane().add(TITULO_EMAIL_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, -1, -1));

        TITULO_LOGIN_SIG2.setBackground(new java.awt.Color(0, 0, 0));
        TITULO_LOGIN_SIG2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TITULO_LOGIN_SIG2.setForeground(new java.awt.Color(255, 243, 211));
        TITULO_LOGIN_SIG2.setText("SISTEMA INTEGRADO DE GESTÃO");
        getContentPane().add(TITULO_LOGIN_SIG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 410, 30));

        LOGO_BOMPAO_LOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1730577049734-d53051c6-8d4a-44e0-9eec-101dc7bcf838_1_2-removebg (1).png"))); // NOI18N
        LOGO_BOMPAO_LOGIN.setText("jLabel9");
        getContentPane().add(LOGO_BOMPAO_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 180, -1));

        TITULO_BOMPAO.setBackground(new java.awt.Color(0, 0, 0));
        TITULO_BOMPAO.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        TITULO_BOMPAO.setForeground(new java.awt.Color(255, 243, 211));
        TITULO_BOMPAO.setText("BOM PÃO");
        getContentPane().add(TITULO_BOMPAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 500, 80));

        BT_ENTRAR_LOGIN.setBackground(new java.awt.Color(255, 243, 211));
        BT_ENTRAR_LOGIN.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        BT_ENTRAR_LOGIN.setForeground(new java.awt.Color(68, 45, 37));
        BT_ENTRAR_LOGIN.setText("ENVIAR CÓDIGO");
        BT_ENTRAR_LOGIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_ENTRAR_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ENTRAR_LOGINActionPerformed(evt);
            }
        });
        getContentPane().add(BT_ENTRAR_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 160, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setText("PASSO 3");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, -1, 30));

        jTextField7.setBackground(new java.awt.Color(255, 243, 211));
        jTextField7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(68, 45, 37));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 250, 40));

        jTextField9.setBackground(new java.awt.Color(255, 243, 211));
        jTextField9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(68, 45, 37));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 250, 40));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel10.setText("RECUPERAR ACESSO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 450, 30));

        BT_ENTRAR_LOGIN1.setBackground(new java.awt.Color(255, 243, 211));
        BT_ENTRAR_LOGIN1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        BT_ENTRAR_LOGIN1.setForeground(new java.awt.Color(68, 45, 37));
        BT_ENTRAR_LOGIN1.setText("VALIDAR CÓDIGO");
        BT_ENTRAR_LOGIN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_ENTRAR_LOGIN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ENTRAR_LOGIN1ActionPerformed(evt);
            }
        });
        getContentPane().add(BT_ENTRAR_LOGIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 170, -1));

        BT_ENTRAR_LOGIN2.setBackground(new java.awt.Color(255, 243, 211));
        BT_ENTRAR_LOGIN2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        BT_ENTRAR_LOGIN2.setForeground(new java.awt.Color(68, 45, 37));
        BT_ENTRAR_LOGIN2.setText("ENVIAR");
        BT_ENTRAR_LOGIN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_ENTRAR_LOGIN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ENTRAR_LOGIN2ActionPerformed(evt);
            }
        });
        getContentPane().add(BT_ENTRAR_LOGIN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 540, -1, -1));

        jTextField10.setBackground(new java.awt.Color(255, 243, 211));
        jTextField10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(68, 45, 37));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 250, 40));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel11.setText("PASSO 1");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, 30));

        TITULO_EMAIL_LOGIN1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TITULO_EMAIL_LOGIN1.setForeground(new java.awt.Color(255, 243, 211));
        TITULO_EMAIL_LOGIN1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TITULO_EMAIL_LOGIN1.setText("Digite seu e-mail");
        getContentPane().add(TITULO_EMAIL_LOGIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel12.setText("PASSO 2");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, 30));

        TITULO_EMAIL_LOGIN2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TITULO_EMAIL_LOGIN2.setForeground(new java.awt.Color(255, 243, 211));
        TITULO_EMAIL_LOGIN2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TITULO_EMAIL_LOGIN2.setText("Digite o código recebido");
        getContentPane().add(TITULO_EMAIL_LOGIN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Voltar para tela incial");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, -1, -1));

        IMG_BACKGRUND_LOGIN.setForeground(new java.awt.Color(230, 25, 117));
        IMG_BACKGRUND_LOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Home.png.png"))); // NOI18N
        getContentPane().add(IMG_BACKGRUND_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ENTRAR_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ENTRAR_LOGINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ENTRAR_LOGINActionPerformed

    private void BT_ENTRAR_LOGIN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ENTRAR_LOGIN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ENTRAR_LOGIN1ActionPerformed

    private void BT_ENTRAR_LOGIN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ENTRAR_LOGIN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ENTRAR_LOGIN2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telarecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telarecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telarecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telarecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telarecovery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ENTRAR_LOGIN;
    private javax.swing.JButton BT_ENTRAR_LOGIN1;
    private javax.swing.JButton BT_ENTRAR_LOGIN2;
    private javax.swing.JLabel IMG_BACKGRUND_LOGIN;
    private javax.swing.JLabel LOGO_BOMPAO_LOGIN;
    private javax.swing.JLabel TITULO_BOMPAO;
    private javax.swing.JLabel TITULO_EMAIL_LOGIN;
    private javax.swing.JLabel TITULO_EMAIL_LOGIN1;
    private javax.swing.JLabel TITULO_EMAIL_LOGIN2;
    private javax.swing.JLabel TITULO_LOGIN_SIG2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
